# Generated by Django 5.0.4 on 2024-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name="Vendor's name")),
                ('contact_details', models.TextField(verbose_name='Contact information of the vendor')),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('on_time_delivery_rate', models.FloatField(help_text='Tracks the percentage of on-time deliveries.', verbose_name='On-time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(help_text='Average rating of quality based on purchase orders.', verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(help_text='Average time taken to acknowledge purchase orders.', verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(help_text='Percentage of purchase orders fulfilled successfully.', verbose_name='Fulfillment Rate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
