# Generated by Django 5.0.4 on 2024-05-02 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historical_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('name', models.CharField(max_length=50, verbose_name="Vendor's name")),
                ('contact_details', models.TextField(verbose_name='Contact information of the vendor')),
                ('vendor_code', models.CharField(max_length=50, unique=True)),
                ('on_time_delivery_rate', models.FloatField(help_text='Tracks the percentage of on-time deliveries.', verbose_name='On-time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(help_text='Average rating of quality based on purchase orders.', verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(help_text='Average time taken to acknowledge purchase orders.', verbose_name='Average Response Time')),
                ('fulfillment_rate', models.FloatField(help_text='Percentage of purchase orders fulfilled successfully.', verbose_name='Fulfillment Rate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='historical_performance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='historical_performance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated_at'),
        ),
        migrations.AlterField(
            model_name='historical_performance',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor'),
        ),
        migrations.DeleteModel(
            name='Vender',
        ),
    ]
